CREATE TABLE genre (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    genre_abbreviation_name VARCHAR(255) UNIQUE NOT NULL,
    genre_name VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (id),
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;