CREATE TABLE package_image (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    package_image_url VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;